spring:
  application:
    name: likelion-spring

  datasource:
    url: jdbc:mysql://likelion-database.c5ucqyyiepkl.ap-northeast-2.rds.amazonaws.com/likelion
    username: likelion
    password: inwooKim1004!